### ISSUE TITLE
Hi-

### ISSUE THREAD

**Issue by BmePrecision** [shopgirl284/CMT.bundle#5]
new to using your bundle, thanks for creating it.  It looks like there are issues when the first commercial comes up for new recent episodes.  when the commercial comes on the video stops playing.  a show says its only 15 min long when in reality it should be 1 hr long.  if you could look into this would greatly appreciate it!!!! thanks!

**Comment by shopgirl284** [comment]
This channel, like all Plex channels for Viacom network websites, breaks its videos into multiple parts. You may want to test another Viacom network channels to see if this issue is unique to the CMT channel or related to your Plex player accessing any Plex channels for Viacom network websites, since they all break their videos into parts the same way. The Comedy Central and Spike channels are also Plex channels that access Viacom network websites and are available through the Channel Directory.

What you are seeing is the length of the first part of the video. When the first part ends, your Plex player should automatically start the next part of the videos after a few seconds. Sometimes the player will return to the previous screen before it starts playing the next section so you have to be patient for a minute. 

First make sure your Plex player can handle videos that are broken into parts and that the way in which it plays videos from the Watch Later option may be different than how it plays videos from the Plex channel. If your Plex player can handle videos in parts, also realize that these videos are hosted by the website for which the channel is named, in this case the CMT website. And the speed of their video servers can vary. 

So sometimes the amount of time it takes the Plex player to load the next part for larger quality videos can cause the player to time out. If your player has the option, you can try choosing a lower quality version of the video, for example the 420p version instead of the 720p version. This is usually available through media options. For example, in Plex Web (using a web browser to access Plex), the media options are listed under ... then info and to choose a different quality, once a video starts playing, you can choose the icon that looks like three ethernet cables in the upper right hand corner of the play screen.

Also see this forum post where the handling of channels where videos that are in parts are discussed -  https://forums.plex.tv/discussion/comment/1114977/#Comment_1114977 and the CMT channel plugin Thread at https://forums.plex.tv/discussion/81341/rel-cmt-plugin.

**Comment by BmePrecision** [comment]
Thanks so much for your help,  it finally loaded after the video paused commercial break. I really  appreciate the quick response. Also by any chance do you know of a working Bravo and or AMC bundle? The Bravo one I downloaded on github doesn't work. It just says error when opening

Thanks again!

**Comment by shopgirl284** [comment]
The only Bravo one I know of is mine. And you are right it is giving an error. I will have to take a look at it. I only use it to watch the Top Chef Last Chance Kitchen videos, but I have not tried it in a while so I did not know there was an issue. I have opened an issue for it at https://github.com/shopgirl284/Bravo.bundle/issues/2

It really doesn't give you access to many videos on the Bravo website anyway (it is kind of like the Plex SyFy channel), that is why I created it but never "advertised" it, I did not even take the time to add a default image for it. 

The last time I did use it, there were no unlocked (don't require TV provider info) full episodes available.I had tweaked the code for the Bravo version to include any video that were longer than 5 minutes, so it would pick up the web only series like Last Chance Kitchen. Often that and the Watch What Happens after show are the only videos available. 

Also be aware that my Bravo channel uses the Plex NBC channel code. So if you cannot use the NBC channel, then my Bravo channel will not work for you. NBC/Universal uses eHLS format for their videos and that format will only work on some Plex Players right now. 

And though there are quite a few unlocked full episodes for NBC, there are not for the other NBC/Universal stations.  The code I used actually pulls their Ipad app data not what is shown on the websites.  Because it uses the Ipad app, even if a full episode is available on their website, it may not be available in the Ipad app and therefore the Plex channel.
